language: python
env:
  global:
  - secure: f9tUziw8T7DIjfkieH0QuMOvXRRwTw+7RUMB7DJW9t8ZVrzMnlv4TAu3sT1u70JOe8XABqbPNQwssLotTfs/MOknTEUgw6Jo94pDWsbdBJKUs1e4IBOZDTDyflsdth0BOFOZEfOqCSEj05Tn+OIL0NLHmZsjmRhCt0F+n4vLgos=
  - secure: nSvMgqBsJTqYvpwDtOmAicnpha5RI4skPixe7/Gfv11i20c41Lx73GX/At8DMgkbNVOtSPQbxLzJNGeylho0tAq8LNMxcVnTK47BCVEutA6LfNbiTb14WPkzg2F5VaS/yDal7VSyP13plJV4KbTcyMoz+8miyDtqsPWei45cfEg=
  - BOB_UPLOAD_WHEEL=1
matrix:
  include:
  - python: 2.7
    env:
    - BOB_DOCUMENTATION_SERVER=https://www.idiap.ch/software/bob/docs/latest/bioidiap/%s/master
  - python: 3.3
  - python: 3.4
  - python: 3.5
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install -qq --force-yes libboost-all-dev libblitz1-dev libjpeg8-dev libnetpbm10-dev libpng12-dev libtiff4-dev libgif-dev
- sudo apt-get install -qq --force-yes libhdf5-serial-dev libvl-dev texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended gfortran
- sudo apt-get install -qq --force-yes libatlas-dev libatlas-base-dev liblapack-dev
- pip install --upgrade pip
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel sphinx nose numpy scipy matplotlib coverage cpp-coveralls
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel --pre -r requirements.txt coveralls
install:
- python bootstrap-buildout.py
- CPPFLAGS=--coverage LDFLAGS=--coverage ./bin/buildout buildout:debug=false buildout:develop=. buildout:extensions=bob.buildout buildout:auto-checkout=
script:
- ./bin/python -c 'import pkg_resources; from bob.ip.facedetect import get_config; print(get_config())'
- ./bin/coverage run --source=bob.ip.facedetect ./bin/nosetests -sv
- ./bin/sphinx-build -b doctest doc sphinx
- ./bin/sphinx-build -b html doc sphinx
after_success:
- cpp-coveralls --build-root=`pwd` --exclude=src --exclude-pattern=".*Compiler.*" --dump=cpp_cov.json
- coveralls --merge=cpp_cov.json
- wget https://raw.githubusercontent.com/bioidiap/bob.extension/master/scripts/upload-{sphinx,wheel}.sh
- chmod a+x upload-sphinx.sh upload-wheel.sh
- ./upload-sphinx.sh
- ./upload-wheel.sh
